osx_image: xcode10
language: objective-c
xcode_project: Taskig.xcodeproj
xcode_scheme: TaskigOSX

branches:
  only:
    - master

before_install:
  - gem install cocoapods

script: 
  - xcodebuild clean build test -project Taskig.xcodeproj -scheme TaskigiOS -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - pod lib lint Taskig.podspec
